[package]
name = "sensor-playground-mlx90615"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sensor_node_mlx90615"
path = "src/main.rs"

[dependencies]
common = { package = "sensor-playground-common", path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }
fastrand = { workspace = true }
